Models/Talkshow.cs
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BIT_STAMP.Models
{
    [Table("Talkshow")]
    public class Talkshow
    {
        [Key]
        public int TalkshowId { get; set; }

        [Required]
        public string UserId { get; set; }
        [Display(Name = "Attendees")]
        [ForeignKey("UserId")]
        public Us? User { get; set; }

        [Display(Name = "Confirm")]
        public bool? IsConfirm { get; set; } = false;

        [Display(Name = "Check in")]
        public bool? IsCheckIn { get; set; } = false;

        [Required]
        public bool IsDeleted { get; set; } = false;
        public Talkshow() { }
        public Talkshow(int TalkshowId, string userID, Us user, bool? isConfirm, bool isCheckIn, bool isDeleted)
        {
            this.TalkshowId = TalkshowId;
            this.UserId = userID;
            this.User = user;
            this.IsConfirm = isConfirm;
            this.IsDeleted = isDeleted;
            this.IsCheckIn = isCheckIn;
        }
    }
}

Controllers/RankingController.cs
using BIT_STAMP.Data;
using BIT_STAMP.Models;
using BIT_STAMP.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BIT_STAMP.Controllers
{
    public class RankingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public RankingController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Ranking(string? currentFilter, string? searchString, int page = 1)
        {
            var product = _context.Products.OrderByDescending(m => m.VoteAmount).ToList();
            
            var group = _context.GroupUsers;
            ViewBag.Group = group.ToList();

            int pageSize = 9;
            var ranking = (page - 1) * pageSize;
            ViewBag.Rankings = ranking;

            var members = _context.Relationships.Include(m => m.us);
            ViewBag.Members = members.ToList();
            if (searchString != null)
            {
                page = 1;
                List<int> rank = new List<int>();
                var listProduct = _context.Products.Where(m => m.ProductName.Trim().ToLower().Contains(searchString.Trim().ToLower())).OrderByDescending(m => m.VoteAmount).ToList();
                for (int i = 0; i < listProduct.Count; i++)
                {
                    for (int j = 0; j < product.Count; j++)
                    {
                        if (listProduct[i].ProductId == product[j].ProductId)
                        {
                            rank.Add(j+1);
                            break;
                        }
                    }                    
                }
                ViewBag.SearchRank = rank;
                ViewBag.SearchProduct = listProduct.ToList();
            }
            else
            {
                searchString = currentFilter;
                List<Product> products = new List<Product>();
                ViewBag.SearchProduct = products;
            }
            ViewData["CurrentFilter"] = searchString;

            var vote = _context.Votes.ToList();
            ViewBag.Vote = vote.ToList();
            
            var top20 = _context.Products.OrderByDescending(m => m.VoteAmount).Take(20).ToList();
            ViewBag.Top20 = top20.ToList();

            int totalCount = product.Count;
            int skip = (page - 1) * pageSize;
            var pagedItems = product.Skip(skip).Take(pageSize).ToList();

            PageViewModel<Product> mymodel = new PageViewModel<Product>
            {
                Items = pagedItems,
                TotalCount = totalCount,
                PageSize = pageSize,
                PageIndex = page
            };
            return View(mymodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Voting(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }
            if (id == null || id == 0 || _context.Products == null)
            {
                return NotFound();
            }
            var product = _context.Products.FirstOrDefault(m => m.ProductId == id);
            if (product == null)
            {
                TempData["error"] = "Tác phẩm không tồn tại";
                return NotFound();
            }
            var vote = _context.Votes.FirstOrDefault(m => m.ProductId == id && m.UserId.Equals(user.Id));
            if (vote != null)
            {
                TempData["error"] = "Bạn đã bình chọn cho tác phẩm này rồi";
                return NotFound();
            }

            Vote newVote = new Vote();
            newVote.ProductId = (int)id;
            newVote.UserId = user.Id;
            _context.Votes.Add(newVote);
            _context.SaveChanges();

            product.VoteAmount += 1;
            _context.Products.Update(product);
            _context.SaveChanges();

            TempData["success"] = "Bạn đã vote thành công cho tác phẩm: " + product.ProductName;

            return Ok();
        }

        public async Task<IActionResult> Details(int? id)
        {
            var product = _context.Products.FirstOrDefault(m => m.ProductId == id);

            if (product == null)
            {
                return NotFound();
            }
            var group = _context.GroupUsers;
            ViewBag.Group = group.ToList();            

            return PartialView("RankingProductInforPartial", product);
        }
    }
}

Controllers/TalkshowController.cs
using BIT_STAMP.Data;
using BIT_STAMP.Models;
using BIT_STAMP.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Encodings.Web;

namespace BIT_STAMP.Controllers
{
    public class TalkshowController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;

        public TalkshowController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
        }
        public async Task<IActionResult> HomeRegisterTalkshow()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                ViewData["School"] = new SelectList(_context.Schools, "SchoolId", "SchoolName");
                var atd = _context.Us.FirstOrDefault(u => u.Email.Equals(user.Email) && u.UsMssv != null);

                if(atd != null) { 
                    ViewBag.atd = atd;
                    ViewData["SelectedSchool"] = new SelectList(_context.Schools, "SchoolId", "SchoolName", atd.SchoolId);
                }

                var talkshow = _context.Talkshows.Count();
                ViewBag.talkshow = talkshow;

                return View();
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterInfor(string PhoneNumber, string UsMssv, int? SchoolId, string FullName)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }
            if (PhoneNumber != null && UsMssv != null && SchoolId != null && FullName != null)
            {
                var atd = _context.Us.FirstOrDefault(m => m.Email.Equals(user.Email));
                if (atd == null)
                {
                    var findMssv = _context.Us.Where(m => m.UsMssv.Trim().ToLower().Equals(UsMssv.Trim().ToLower())).Count();
                    if (findMssv > 0)
                    {
                        TempData["error"] = "Mã số sinh viên đã được đăng ký với tài khoản Email khác";
                        return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
                    }

                    Us newAttendee = new Us();
                    newAttendee.STT = _context.Us.OrderBy(m => m.STT).Last().STT + 1;
                    newAttendee.PhoneNumber = PhoneNumber;
                    newAttendee.UsMssv = UsMssv;
                    newAttendee.FullName = FullName;
                    newAttendee.SchoolId = (int)SchoolId;
                    newAttendee.Email = user.Email;

                    _context.Us.Add(newAttendee);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Thêm thông tin thành công";
                }
                else
                {
                    TempData["error"] = "Thông tin đã tồn tại";
                }

            }
            return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeInfor(string PhoneNumber, string UsMssv, int? SchoolId, string FullName)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }
            if (PhoneNumber != null && UsMssv != null && SchoolId != null && FullName != null)
            {
                var atd = _context.Us.FirstOrDefault(m => m.Email.Equals(user.Email));
                if (atd == null)
                {
                    TempData["error"] = "Thông tin không tồn tại";
                }
                else
                {
                    var findMssv = _context.Us.Where(m => !m.Email.Equals(user.Email) && m.UsMssv.Trim().ToLower().Equals(UsMssv.Trim().ToLower())).Count();
                    if (findMssv > 0)
                    {
                        TempData["error"] = "Mã số sinh viên đã tồn tại";
                        return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
                    }

                    atd.STT = _context.Us.OrderBy(m => m.STT).Last().STT + 1;
                    atd.PhoneNumber = PhoneNumber;
                    atd.UsMssv = UsMssv;
                    atd.FullName = FullName;
                    atd.SchoolId = (int)SchoolId;

                    _context.Us.Update(atd);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Thay đổi thông tin thành công";
                }

            }
            return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterTalkshow()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }

            var now = DateTime.Now;
            var end = new DateTime(2024, 1, 22, 17, 59, 59);

            if (now > end || _context.Talkshows.Count() >= 320)
            {
                TempData["error"] = "Form đăng ký tham gia đã đóng do quá hạn hoặc đủ số lượng tham gia.";
                return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
            }

            var atd = _context.Us.FirstOrDefault(u => u.Email.Equals(user.Email) && u.UsMssv != null);
            /*var atd = _context.Us.FirstOrDefault(m => m.Id.Equals(user.Id));*/
            if (atd == null)
            {
                TempData["error"] = "Bạn phải thêm thông tin cá nhân trước.";
            }
            else
            {
                var registerUser = _context.Talkshows.FirstOrDefault(m => m.UserId.Equals(atd.Id));
                if (registerUser != null)
                {
                    TempData["error"] = "Bạn đã đăng ký tham gia Talkshow thành công, không thể đăng ký thêm.";
                }
                else
                {
                    Talkshow register = new Talkshow();
                    register.UserId = atd.Id;

                    _context.Talkshows.Add(register);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Bạn đã đăng ký tham gia Talkshow thành công!";

                    /*await _emailSender.SendEmailAsync(
                        user.Email,
                        "[NO-REPLY] Đăng ký tham gia Talkshow S.T.A.M.P 2023",
                        $"Bạn đã đăng ký tham gia Talkshow S.T.A.M.P 2023 thành công. Nếu đây không phải hoạt động của bạn, vui lòng xóa email này.");*/
                }
            }          
            return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BIT_STAMP.Controllers
{
    public class UserController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<UserController> _logger;

        public UserController(SignInManager<IdentityUser> signInManager, ILogger<UserController> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }
        public IActionResult Info()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Logout(string returnUrl = null) {
            /*await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);*/
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Talkshow/HomeRegisterTalkshow.cshtml
@using BIT_STAMP.Models
@model BIT_STAMP.Models.Us
@{
    ViewData["Title"] = "Trang cá nhân";
    var now = DateTime.Now;
    var end = new DateTime(2024, 1, 22, 17, 59, 59);
}
    <!-- Banner -->
    <div class="banner-container">
        <img class="stamplogo" src="~/image/shared/stamplogo-big.png" alt="">
    </div>
    <!-- Avatar người dùng -->
    <div class="profile-container">
        <div class="avatar-frame">
             <!-- Sử dụng thẻ img để hiển thị hình ảnh avatar -->
            <img src="~/image/UserProfile/user-square.png" alt="">
                <button class="setting-button" onclick="showProfilePopup()">
                    <img src="~/image/UserProfile/setting.png">
                </button>
        </div>
        <span class="account-name">
            @User.Identity.Name
        </span>
    </div>

    <!-- Các nút trang chủ,đăng kí, bảng xếp hạng -->
    <div class="button-container row">
        <button class="col-3 home-button" id="home-button">
            <a class="nav-link item" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
        </button>
        <button class="col-3 ranking-button" id="ranking-button">
            <a class="nav-link item" asp-area="" asp-controller="Ranking" asp-action="Ranking">Bảng xếp hạng</a>
        </button>
        <button class="col-3 register-button" id="register-button">
            <a class="nav-link item" href="#register">Đăng ký Talkshow</a>
        </button>
    </div>

    

<!-- Popup thay đổi thông tin cá nhân -->
    <div class="overlay" id="overlay" style="display:none"></div>
    <div id="modalOne" class="modal" style="display:none">
        <div class="modal-content">
            <div class="contact-form" id="contact-form">
            @if (ViewBag.atd == null)
            {
                <form class="change-profile" asp-controller="Talkshow" asp-action="RegisterInfor" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <h2>THÔNG TIN CÁ NHÂN</h2>
                    <div>
                        @* <div class="modify-avatar-frame">
                            <img src="~/image/UserProfile/user-circle-add.png" class="modify-avatar-img">
                        </div> *@
                    <div class="input-box">
                            <label> Họ và tên </label>
                            <input asp-for="FullName" class="glow" value="" />
                            <span asp-validation-for="FullName" class="text-danger"></span>
                            
                        </div>
                        <div class="input-box">
                            <label> Trường </label>
                            <select asp-for="SchoolId" class="glow" asp-items="ViewBag.School"></select>
                            <span asp-validation-for="SchoolId" class="text-danger"></span>
                            
                        </div>
                        <div class="input-box">
                            <label> MSSV </label>
                            <input asp-for="UsMssv" class="glow" value="" />
                            <span asp-validation-for="UsMssv" class="text-danger"></span>
                            
                        </div>
                        <div class="input-box">
                            <label> Số điện thoại </label>
                            <input type="number" inputmode="numeric" pattern="[0-9]*" asp-for="PhoneNumber" class="glow" value="" type="number" required/>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            
                        </div>
                    </div>
                    <div class="info-button-container">
                        <button class="exit-button" id="exit-button" type="button" onclick="hideProfilePopup()"> Thoát </button>
                        <button class="save-button" id="save-button" type="submit"> Lưu thông tin </button>                                                                   
                    </div>
                </form>
            }
            else
            {
                Us atd = ViewBag.atd;                
                <form class="change-profile" asp-controller="Talkshow" asp-action="ChangeInfor" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <h2>THAY ĐỔI THÔNG TIN CÁ NHÂN</h2>
                    <div>
                        @* <div class="modify-avatar-frame">
                            <img src="~/image/UserProfile/user-circle-add.png" class="modify-avatar-img">
                        </div> *@
                    <div class="input-box">
                            <label> Họ và tên </label>
                            <input asp-for="FullName" class="glow" value="@atd.FullName" />
                            <span asp-validation-for="FullName" class="text-danger"></span>
                            
                        </div>
                        <div class="input-box">
                            <label> Trường </label>
                            <select asp-for="SchoolId" class="glow" asp-items="ViewBag.SelectedSchool"></select>
                            <span asp-validation-for="SchoolId" class="text-danger"></span>
                            
                        </div>
                        <div class="input-box">
                            <label> MSSV </label>
                            <input asp-for="UsMssv" class="glow" value="@atd.UsMssv" />
                            <span asp-validation-for="UsMssv" class="text-danger"></span>
                            
                        </div>
                        <div class="input-box">
                            <label> Số điện thoại </label>
                            <input type="number" inputmode="numeric" pattern="[0-9]*" asp-for="PhoneNumber" class="glow" value="@atd.PhoneNumber" type="number" required/>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            
                        </div>
                    </div>
                    <div class="info-button-container">
                        <button class="exit-button" id="exit-button" type="button" onclick="hideProfilePopup()"> Thoát </button>
                        <button class="save-button" id="save-button" type="submit"> Lưu thông tin mới </button>                                                      
                    </div>
                </form>
            }
                
            </div>
        </div>
    </div>
    <div class="content-container">
        <div class="content justify-content-center">
            <a class="register-talkshow" href="#register">Đăng kí Talkshow</a>
        </div>
</div>
@if (now <= end && ViewBag.talkshow < 320)
{
   <form asp-controller="Talkshow" asp-action="RegisterTalkshow" method="post">
        <div id ="register" class="col-lg-6 col-md-12 col-sm-12 mx-auto d-flex">
            <div class="talkshow-container justify-content-center">
                <div class="stamp-frame">
                    @* <img src="~/image/UserProfile/image3.png" class="stamp-img"> *@
                    <img src="~/image/userprofile/ấn phẩm tọa đàm.png" class="stamp-img" />
                </div>
                <div  class="info-container">
                    <div class=info-content-container>
                        <span class="info-name">S.T.A.M.P 2023 - Stand Together And Make Protection</span>
                            <h3 class="info-content">là cuộc thi về thiết kế và triển lãm tem thư được tổ chức bởi Đoàn - Hội khoa Công nghệ thông tin kinh doanh</h3>
                    </div>
                </div>
                <div class="talkshow-button-container">

                        @if (ViewBag.atd == null)
                        {
                            <button class="register-talkshow-button" onclick="showProfilePopup()" type="button">Đăng kí</button>
                        }
                        else
                        {
                            <button class="register-talkshow-button" type="submit">Đăng kí</button>
                        }
                              
                </div>
            </div>
        </div>
    </form>
}
else
{
    <br />
    <br />
    <br />
    <h3 class="container">Form đăng ký tham gia Talkshow đóng do quá hạn hoặc đủ số lượng tham gia, cảm ơn các bạn đã quan tâm chương trình và hẹn gặp lại ở các hoạt động khác của BIT.</h3>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
}

<form class="logout" asp-area="" asp-controller="User" asp-action="Logout" method="post" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
    @* <button id="login-button" class="login-button" type="submit">Đăng xuất</button> *@
    <button id="login-button" class="login-button" type="submit">Đăng xuất</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @* <script>
        // Lấy tất cả các thẻ <a> có class "register-stamp" và "register-talkshow"
        var stampLink = document.querySelector('.register-stamp');
        var talkshowLink = document.querySelector('.register-talkshow');

        // Thêm sự kiện click cho thẻ "Register Stamp"
        stampLink.addEventListener('click', function (event) {
            stampLink.style.textDecoration = 'underline'; // Thêm gạch chân
            talkshowLink.style.textDecoration = 'none'; // Loại bỏ gạch chân ở thẻ "Register Talkshow"
        });

        // Thêm sự kiện click cho thẻ "Register Talkshow"
        talkshowLink.addEventListener('click', function (event) {
            talkshowLink.style.textDecoration = 'underline'; // Thêm gạch chân
            stampLink.style.textDecoration = 'none'; // Loại bỏ gạch chân ở thẻ "Register Stamp"
        });
    </script> *@
    <!-- JavaScript điều khiển popup thay đổi thông tin cá nhân -->
    <script>
        function showProfilePopup(){
            const modalOne = document.getElementById('modalOne');
            var body = document.querySelector("body");
            var overlay = document.getElementById("overlay");

            modalOne.style.display = 'block';
            document.body.style.overflow = 'hidden'; // Tắt cuộn
            overlay.style.display = 'block'; // Hiển thị nền mờ
        }
        function hideProfilePopup(){
            const modalOne = document.getElementById('modalOne');
            var body = document.querySelector("body");
            var overlay = document.getElementById("overlay");

            modalOne.style.display = 'none';
            document.body.style.overflow = 'auto'; // Tắt cuộn
            overlay.style.display = 'none'; // Hiển thị nền mờ
        }
        @*const modalOne = document.getElementById('modalOne');
        const settingButton = document.getElementById('setting-button');
        const exitButton = document.querySelector(".exit-button");
        settingButton.addEventListener('click', () => {
            modalOne.style.display = 'block';
            document.body.style.overflow = 'hidden'; // Tắt cuộn
            overlay.style.display = 'block'; // Hiển thị nền mờ
        });
        exitButton.addEventListener('click', () => {
            modalOne.style.display = 'none';
            document.body.style.overflow = 'auto'; // Tắt cuộn
            overlay.style.display = 'none'; // Hiển thị nền mờ
        });*@
    </script>
    @* <script>
        // JavaScript chuyển trang
        var rankingButton = document.querySelector(".ranking-button");
        rankingButton.addEventListener("click", function () {
            window.location.href = "HomeRanking";
        });
        var homeButton = document.querySelector(".home-button");
        homeButton.addEventListener("click", function () {
            window.location.href = "HomeUser";
        });
    </script> *@
}
@section Styles{
    <link rel="stylesheet" href="~/css/homeregister.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/homeregistertalkshow.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/userprofile.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/homeregisterstamp.css" asp-append-version="true" />
}