Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace BIT_STAMP.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

Controllers/NewsController.cs
/*using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BIT_STAMP.Controllers
{
    public class NewsController : Controller
    {
        // GET: NewsController
        public ActionResult News()
        {
            return View();
        }

        // GET: UsController/Details/5
        public ActionResult NewsDetail(int id)
        {
            return View();
        }

        // GET: UsController/Create
        *//*public ActionResult Create()
        {
            return View();
        }

        // POST: UsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }*//*
    }
}
*/

Controllers/RankingController.cs
using BIT_STAMP.Data;
using BIT_STAMP.Models;
using BIT_STAMP.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BIT_STAMP.Controllers
{
    public class RankingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public RankingController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Ranking(string? currentFilter, string? searchString, int page = 1)
        {
            var product = _context.Products.OrderByDescending(m => m.VoteAmount).ToList();
            
            var group = _context.GroupUsers;
            ViewBag.Group = group.ToList();

            int pageSize = 9;
            var ranking = (page - 1) * pageSize;
            ViewBag.Rankings = ranking;

            var members = _context.Relationships.Include(m => m.us);
            ViewBag.Members = members.ToList();
            if (searchString != null)
            {
                page = 1;
                List<int> rank = new List<int>();
                var listProduct = _context.Products.Where(m => m.ProductName.Trim().ToLower().Contains(searchString.Trim().ToLower())).OrderByDescending(m => m.VoteAmount).ToList();
                for (int i = 0; i < listProduct.Count; i++)
                {
                    for (int j = 0; j < product.Count; j++)
                    {
                        if (listProduct[i].ProductId == product[j].ProductId)
                        {
                            rank.Add(j+1);
                            break;
                        }
                    }                    
                }
                ViewBag.SearchRank = rank;
                ViewBag.SearchProduct = listProduct.ToList();
            }
            else
            {
                searchString = currentFilter;
                List<Product> products = new List<Product>();
                ViewBag.SearchProduct = products;
            }
            ViewData["CurrentFilter"] = searchString;

            var vote = _context.Votes.ToList();
            ViewBag.Vote = vote.ToList();
            
            var top20 = _context.Products.OrderByDescending(m => m.VoteAmount).Take(20).ToList();
            ViewBag.Top20 = top20.ToList();

            int totalCount = product.Count;
            int skip = (page - 1) * pageSize;
            var pagedItems = product.Skip(skip).Take(pageSize).ToList();

            PageViewModel<Product> mymodel = new PageViewModel<Product>
            {
                Items = pagedItems,
                TotalCount = totalCount,
                PageSize = pageSize,
                PageIndex = page
            };
            return View(mymodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Voting(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }
            if (id == null || id == 0 || _context.Products == null)
            {
                return NotFound();
            }
            var product = _context.Products.FirstOrDefault(m => m.ProductId == id);
            if (product == null)
            {
                TempData["error"] = "Tác phẩm không tồn tại";
                return NotFound();
            }
            var vote = _context.Votes.FirstOrDefault(m => m.ProductId == id && m.UserId.Equals(user.Id));
            if (vote != null)
            {
                TempData["error"] = "Bạn đã bình chọn cho tác phẩm này rồi";
                return NotFound();
            }

            Vote newVote = new Vote();
            newVote.ProductId = (int)id;
            newVote.UserId = user.Id;
            _context.Votes.Add(newVote);
            _context.SaveChanges();

            product.VoteAmount += 1;
            _context.Products.Update(product);
            _context.SaveChanges();

            TempData["success"] = "Bạn đã vote thành công cho tác phẩm: " + product.ProductName;

            return Ok();
        }

        public async Task<IActionResult> Details(int? id)
        {
            var product = _context.Products.FirstOrDefault(m => m.ProductId == id);

            if (product == null)
            {
                return NotFound();
            }
            var group = _context.GroupUsers;
            ViewBag.Group = group.ToList();            

            return PartialView("RankingProductInforPartial", product);
        }
    }
}

Controllers/VoteController.cs
using BIT_STAMP.Data;
using BIT_STAMP.Models;
using BIT_STAMP.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BIT_STAMP.Controllers
{
    public class VoteController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public VoteController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Voting(string? searchString, int page = 1)
        {
            var product = _context.Products.OrderByDescending(m => m.VoteAmount).ToList();
            if(searchString != null)
            {
                var listProduct = _context.Products.Where(m => m.ProductName.Trim().ToLower().Contains(searchString.Trim().ToLower())).ToList();
                ViewBag.SearchProduct = listProduct.ToList();
            }
            else
            {
                List<Product> products = new List<Product>();
                ViewBag.SearchProduct = products;
            }

            var group = _context.GroupUsers;
            ViewBag.Group = group.ToList();

            var vote = _context.Votes.ToList();
            ViewBag.Vote = vote.ToList();

            var top20 = _context.Products.OrderByDescending(m => m.VoteAmount).Take(20).ToList();
            ViewBag.Top20 = top20.ToList();

            int pageSize = 9;
            int totalCount = product.Count;
            int skip = (page - 1) * pageSize;
            var pagedItems = product.Skip(skip).Take(pageSize).ToList();

            PageViewModel<Product> mymodel = new PageViewModel<Product>
            {
                Items = pagedItems,
                TotalCount = totalCount,
                PageSize = pageSize,
                PageIndex = page
            };
            return View(mymodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Voting(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }
            if (id == null || id == 0 || _context.Products == null)
            {
                return NotFound();
            }
            var product = _context.Products.FirstOrDefault(m => m.ProductId == id);
            if (product == null)
            {
                TempData["error"] = "Tác phẩm không tồn tại";
                return NotFound();
            }
            var vote = _context.Votes.FirstOrDefault(m => m.ProductId == id && m.UserId.Equals(user.Id));
            if (vote != null)
            {
                TempData["error"] = "Bạn đã bình chọn cho tác phẩm này rồi";
                return NotFound();
            }

            Vote newVote = new Vote();
            newVote.ProductId = (int)id;
            newVote.UserId = user.Id;
            _context.Votes.Add(newVote);
            _context.SaveChanges();

            product.VoteAmount += 1;
            _context.Products.Update(product);
            _context.SaveChanges();

            TempData["success"] = "Bạn đã vote thành công cho tác phẩm: " + product.ProductName;

            return Ok();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = _context.Products.FirstOrDefault(m => m.ProductId == id);

            if (product == null)
            {
                return NotFound();
            }
            var group = _context.GroupUsers;
            ViewBag.Group = group.ToList();

            var vote = _context.Votes.ToList();
            ViewBag.Vote = vote.ToList();

            return PartialView("VotingProductInforPartial", product);

        }
    }
}

Views/Shared/LoginRequired.cshtml
@{
    Layout = "_BlankLayout";
}
<div class="container-fluid justify-content-center display-none popup" id="popup">
    <div class="row">
        <div class="justify-content-center col-12 popup-title-login">Bạn cần đăng nhập để tiếp tục sử dụng tính năng này</div>
        <div class=" col-12 justify-content-center">
            <button class="justify-content-center like-btn-login" default-color="rgb(217, 217, 217)">
                <a class="login-btn" asp-area="Identity" asp-page="/Account/Login">Đăng nhập</a>
            </button>
        </div>
    </div>
</div>
<div id="overlay" class="display-none"></div>

Views/Shared/Nofitication.cshtml
@if (TempData["success"] != null)
{
   <script src="~/lib/jquery/dist/jquery.min.js"></script> 
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
   <script type="text/javascript">
        toastr.options.closeMethod = 'fadeOut';
        @* toastr.options.extendedTimeOut = 0;
        toastr.options.timeOut = 0; *@ @* Để cho cái toastr không biến mất tới khi click vào nó *@
        toastr.options.closeDuration = 350;
        toastr.options.closeEasing = 'swing';
        toastr.success('@TempData["success"]');
   </script>
}
@if(TempData["error"] != null){
     <script src="~/lib/jquery/dist/jquery.min.js"></script> 
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
          toastr.error('@TempData["error"]');
   </script>
    

}
@if (TempData["LoginSuccess"] != null)
    {
    
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.warning('@TempData["LoginSuccess"]');
        </script>
    }

    @if (TempData["SignUp"] != null)
    {
    
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
        toastr.success('@TempData["SignUp"]');
        </script>
    }

Views/Shared/RankingProductInforPartial.cshtml
@model BIT_STAMP.Models.Product
@{
    List<GroupUser> group = ViewBag.Group;
    Layout = "_BlankLayout";
}
<div class="justify-content-center popup">
    <div class="row">
        <div class="col-6">
            <div class="submission-box">
                <div class="stamp-frame">
                    <img class="stamp-img" src="data:image /jpeg;base64,@(Convert.ToBase64String(@Model.ImageUrl))" alt="product-item">
                </div>
            </div>
        </div>
        <div class="col-6 popup-info">
            <div class="popup-title">@Model.ProductName</div>
            @foreach (var gr in group)
            {
                if (gr.ProductId == Model.ProductId)
                {
                    <div class="popup-author">@gr.GroupName</div>
                }
            }

            <pre class="description scroll">@Model.ProductDescription</pre>
        </div>
    </div>
</div>

Views/Shared/VotingProductInforPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model BIT_STAMP.Models.Product
@{
    List<GroupUser> group = ViewBag.Group;
    List<Vote> votes = ViewBag.Vote;
    Layout = "_BlankLayout";
}
<div class="popup">
    <div class="row ">
        <div class="col-md-6 col-lg-6 col-sm-12 submission-info">
            <p class="title">Tên tác phẩm: @Model.ProductName</p>
            @foreach (var gr in group)
            {
                if (gr.ProductId == Model.ProductId)
                {
                    <p class="author">Tên tác giả: @gr.GroupName</p>
                }
            }

            <p class="description"> Mô tả tác phẩm:</p>
            <pre class="description scroll">@Model.ProductDescription</pre>
        </div>
        <div class="col-md-6 col-lg-6 col-sm-12">
            <div class="stamp-frame">
                <img class="stamp-img" src="data:image /jpeg;base64,@(Convert.ToBase64String(Model.ImageUrl))" alt="product-item">
            </div>
            <div class="container">
                <div class="row justify-content-evenly" style="padding-left: 1%">
                    @{
                        var user = await UserManager.GetUserAsync(User);
                        @if (user != null)
                        {
                            var voted = votes.FirstOrDefault(m => m.ProductId == Model.ProductId && m.UserId.Equals(user.Id));
                            @if (voted != null)
                            {
                                <button class="like-btn-voted col-3">
                                    @Html.AntiForgeryToken()
                                    <p class="like-number">@Model.VoteAmount</p>
                                    <img src="~/icon/like.png" alt="" class="like-icon">
                                </button>
                            }
                            else
                            {
                                <button class="like-btn col-3" onclick="like_action(@Model.ProductId)">
                                    @Html.AntiForgeryToken()
                                    <p id="@Model.ProductId" class="like-number">@Model.VoteAmount</p>
                                    <img src="~/icon/like.png" alt="" class="like-icon">
                                </button>
                            }
                        }
                        else
                        {
                            <button class="like-btn col-3" onclick="loginRequired()">
                                @Html.AntiForgeryToken()
                                <p id="@Model.ProductId" class="like-number">@Model.VoteAmount</p>
                                <img src="~/icon/like.png" alt="" class="like-icon">
                            </button>
                        }
                    }

                    @* <div class="col-3 link-btn">
                    <img src="~/icon/link.png" alt="" class="link-icon">
                    </div>
                    <div class="col-3 facebook-btn">
                    <img src="~/icon/f4.png" alt="" class="facebook-icon">
                    </div> *@
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - STAMP2023</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/base.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/STAMP2023.styles.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/about.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/about-responsive.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/shared-responsive.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/searchbar-style.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" /> @* cái này phải để dưới cùng nếu không sẽ bị ghi đè *@
    <style>
        body {
            /* Set the background image */
            background-image: url('../image/shared/bg.png');
            /* Set background size to a smaller value */
            background-size: 1000px auto; /* Adjust the values as needed */
            /* Set background to repeat */
            background-repeat: repeat;
            /* Center the background image */
            background-position: center center;
            /* Set a fixed background attachment */
            background-attachment: fixed;
        }

            
    </style>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary header">
            <div class="container-fluid" style="height: 100%; background-color: #e5fbf8; border-radius: 10px;">
                <a class="navbar-brand" asp-area="" asp-page="/Index"><img class="logo" src="~/image/shared/stamplogo.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-box" id="navbarNavDropdown">
                    <ul class="navbar-nav header-item">
                        <li class="nav-item">
                            <a class="nav-link item" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        @* <li class="nav-item item">
                            <a class="nav-link item" asp-area="" asp-controller="News" asp-action="News">Tin Tức</a>
                        </li> *@
                        <li class="nav-item item">
                            <a class="nav-link item" asp-area="" asp-controller="AboutUs" asp-action="About">Về S.T.A.M.P</a>
                        </li>
                        <li class="nav-item item">
                            <a class="nav-link item" asp-area="" asp-controller="Vote" asp-action="Voting">Bình chọn</a>
                        </li>
                        <li class="nav-item item">
                            <a class="nav-link item" asp-area="" asp-controller="Ranking" asp-action="Ranking">Xếp hạng</a>
                        </li>
                        <li class="nav-item item">
                            <a class="nav-link item" asp-area="" asp-controller="Exhibition" asp-action="Exhibition">Triển lãm</a>
                        </li>
                    </ul>
                </div>
                
                <div class="login-box" id="navbarNavDropdown">
                    <partial name="_LoginPartial" />
                    
                    @* <ul >
                        <!-- Nút Đăng nhập -->
                        <li >
                            <button id="login-button" class="login-button">
                                <partial name="_LoginPartial" />
                            </button>
                        <!-- 2 nút chức năng -->
                        <li class="nav-item personal-button">
                            <button id="notification-button" class="notification-button">
                                <img class="notify-img" src="~/image/Index/icons/notify.png" alt="">
                            </button>
                            <button id="user-button" class="user-button">
                                 <img class="user-img" src="~/image/Index/icons/user.png" alt="">
                            </button>
                        </li>
                    </ul> *@
                </div>
            </div>
        </nav>
    </header>
    <!-- Phần thông tin đăng nhập tài khoản -->
    @* <div id="custom-form" class="custom-form">
        <form>
            <div class="login-form">
            <h3 class="login-notice">Đăng nhập tài khoản</h3>
            <p class="notice">Bạn cần đăng nhập tài khoản Google của mình để tiếp tục tính năng này<p>
            </div>
            <button class="google-button">
                <span class="google-icon" >Đăng nhập với Google</span>
            </button>
        </form>
        <button class="close-button" id="close-button" >
            <img src="~/image/Index/icons/close.png" class="close-img">
        </button>
    </div> *@
    <!-- Popup thông báo trang cá nhân người dùng -->
    @* <div class="notify-popup" id="notify-popup" style="display:none">
        <h3 class="notify-title"> Thông báo </h3>
        <div class="notify-content"> Hello Stamp </div>
        <div class="notify-content"> Hello Stamp </div>
        <div class="notify-content"> Hello Stamp </div>
        <div class="notify-content"> Hello Stamp </div>
        <div class="notify-content"> Hello Stamp </div>
        <div class="notify-content"> Hello Stamp </div>
    </div> *@
    <div class="container-fluid" style="padding: 0px">
        <partial name="Nofitication" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="container-fluid" style="background-color: #DEDBDB;">
        <div class="row justify-content-around">
            <div class="col-5 footer-column">
                <p class="footer-column__header">Đoàn - Hội <br />Khoa Công nghệ thông tin kinh doanh</p>
            </div>
            <div class="col-4 footer-column">
                <p class="footer-column__header">Contact</p>
            </div>
            <div class="col-3 footer-column">
                <p class="footer-column__header">Follow</p>
            </div>
        </div>
        <div class="row justify-content-around">
            <div class="col-5 footer-column">
                <p class="footer-column__info">Đại học Kinh tế TP. Hồ Chí Minh (UEH)</p>
            </div>
            <div class="col-4 footer-column">
                <p class="footer-column__info"><a href="mailto:doanhoi.bit@ueh.edu.vn" class="" target="_blank">doanhoi.bit@ueh.edu.vn</a></p>
            </div>
            <div class="col-3 footer-column">
                <ul class="footer-column__info">
                    <li><a href="https://www.youtube.com/@@BIT_UEH" class="" target="_blank">Youtube</a></li>
                    <li><a href="https://www.facebook.com/BIT.UEH" class="" target="_blank">Facebook</a></li>
                    <li><a href="https://www.tiktok.com/@@bit.ueh" class="" target="_blank">Tiktok</a></li>
                </ul>
            </div>
        </div>
        <div style="height: 100px"></div>
    </footer>
    <!-- JavaScript thay đổi button đăng nhập thành các nút chức năng khi người dùng đã đăng nhập -->
    @* <script>
        var loginButton = document.getElementById("login-button");
        var notifyButton = document.getElementById("notification-button");
        var userButton = document.getElementById("user-button");
        // Lấy đường dẫn URL từ cửa sổ trình duyệt
        var currentURL = window.location.href;
        // Tạo đối tượng URL từ đường dẫn URL hiện tại
        var url = new URL(currentURL);
        // Lấy phần path của URL (bao gồm "/HomeUser")
        var path = url.pathname;
        // Tách phần cuối của đường dẫn 
        var pathSegments = path.split('/');
        // Lấy phần cuối của mảng 
        var userURL = pathSegments[pathSegments.length - 1];
        if (userURL === "HomeUser" || userURL === "HomeRanking" || userURL === "HomeRegisterStamp"|| userURL === "HomeRegisterTalkshow") {
            loginButton.style.display="none";
            notifyButton.style.display="block";
            userButton.style.display="block";
        }
        else {
            loginButton.style.display="block";
            notifyButton.style.display="none";
            userButton.style.display="none";
        }
    </script> *@
    <!-- JavaScript điều khiển form đăng nhập -->
    @* <script>
        var loginForm=document.getElementById('custom-form');
        var closeButton=document.getElementById('close-button');
        loginButton.addEventListener("click", function() {
            loginForm.style.display = "block";
            document.body.style.overflow = 'hidden'; 
        });
        closeButton.addEventListener("click", function() {
            loginForm.style.display = "none";
            document.body.style.overflow = 'auto'; 
        });
    </script> *@
    <!-- JavaScript điều khiển popup thông báo -->
    @* <script>
        var notifyPopup = document.getElementById("notify-popup");
        var isPopupVisible = false;
        var notifyButton = document.getElementById("notification-button");
         notifyButton.addEventListener("click", function() {
            notifyPopup.style.display = "block";
            isPopupVisible = true;
            document.body.style.overflow = 'hidden'; 
        });
        document.addEventListener("click", function(event) {
        if (isPopupVisible && event.target !== notifyPopup && event.target !== notifyButton) {
            notifyPopup.style.display = "none";
            isPopupVisible = false;
            document.body.style.overflow = 'auto'; }});
    </script> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* <script src="~/js/site.js" asp-append-version="true"></script> *@
    <script src="~/js/navbar.js" asp-append-version="true"></script>
    <script src="~/js/common.js" asp-append-version="true"></script>
    <script src="~/js/timing.js" asp-append-version="true"></script>
    <script src="~/lib/fontawesome/7871494614.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>