Controllers/ExhibitionController.cs
using BIT_STAMP.Data;
using BIT_STAMP.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BIT_STAMP.Controllers
{
    public class ExhibitionController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;

        public ExhibitionController(ApplicationDbContext context, UserManager<IdentityUser> userManager, ILogger<HomeController> logger)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
        }
        public async Task<IActionResult> Exhibition()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var product = _context.Products.OrderByDescending(m => m.VoteAmount).Take(21).ToList();
                var atd = _context.Us.FirstOrDefault(u => u.Email.Equals(user.Email) && u.UsMssv != null);
                ViewBag.atd = atd;

                if(atd != null)
                {
                    var registerUser = _context.Proofs.FirstOrDefault(m => m.UserId.Equals(atd.Id));
                    ViewBag.RegisterUser = registerUser;
                }                

                return View(product);
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Exhibition(IFormFile likefanpageImg, IFormFile upstoryImg, IFormCollection col)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }
            var atd = _context.Us.FirstOrDefault(u => u.Email.Equals(user.Email) && u.UsMssv != null);

            /*var atd = _context.Us.FirstOrDefault(m => m.Id.Equals(user.Id));*/
            if (atd == null)
            {
                TempData["error"] = "Bạn phải thêm thông tin cá nhân trước";
                return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
            }

            var registerUser = _context.Proofs.FirstOrDefault(m => m.UserId.Equals(atd.Id));
            if (registerUser != null)
            {
                TempData["error"] = "Bạn chỉ được bình chọn 01 lần";
                return View();
            }

            if (col.Count > 1 && likefanpageImg != null && upstoryImg != null)
            {
                Proof p = new Proof();

                using (var memoryStream = new MemoryStream())
                {
                    likefanpageImg.CopyTo(memoryStream);
                    p.FanpageImg = memoryStream.ToArray();
                }
                using (var memoryStream = new MemoryStream())
                {
                    upstoryImg.CopyTo(memoryStream);
                    p.StoryImg = memoryStream.ToArray();
                }

                p.UserId = atd.Id;

                _context.Proofs.Add(p);
                await _context.SaveChangesAsync();

                int count = 0;
                foreach (var item in col)
                {
                    if (count < col.Count - 1)
                    {
                        OfflineVoting offVote = new OfflineVoting();
                        offVote.ProductId = int.Parse(item.Key);
                        offVote.ProofId = p.ProofId;
                        count++;

                        _context.OfflineVotings.Add(offVote);
                        await _context.SaveChangesAsync();
                    }
                }

                TempData["success"] = "Bạn đã bình chọn thành công.";

            }
            else
            {
                TempData["error"] = "Bạn cần chọn ít nhất 01 tác phẩm.";
            }
            return RedirectToAction("Exhibition", "Exhibition");
        }
    }
}

Controllers/TalkshowController.cs
using BIT_STAMP.Data;
using BIT_STAMP.Models;
using BIT_STAMP.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Encodings.Web;

namespace BIT_STAMP.Controllers
{
    public class TalkshowController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;

        public TalkshowController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
        }
        public async Task<IActionResult> HomeRegisterTalkshow()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                ViewData["School"] = new SelectList(_context.Schools, "SchoolId", "SchoolName");
                var atd = _context.Us.FirstOrDefault(u => u.Email.Equals(user.Email) && u.UsMssv != null);

                if(atd != null) { 
                    ViewBag.atd = atd;
                    ViewData["SelectedSchool"] = new SelectList(_context.Schools, "SchoolId", "SchoolName", atd.SchoolId);
                }

                var talkshow = _context.Talkshows.Count();
                ViewBag.talkshow = talkshow;

                return View();
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterInfor(string PhoneNumber, string UsMssv, int? SchoolId, string FullName)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }
            if (PhoneNumber != null && UsMssv != null && SchoolId != null && FullName != null)
            {
                var atd = _context.Us.FirstOrDefault(m => m.Email.Equals(user.Email));
                if (atd == null)
                {
                    var findMssv = _context.Us.Where(m => m.UsMssv.Trim().ToLower().Equals(UsMssv.Trim().ToLower())).Count();
                    if (findMssv > 0)
                    {
                        TempData["error"] = "Mã số sinh viên đã được đăng ký với tài khoản Email khác";
                        return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
                    }

                    Us newAttendee = new Us();
                    newAttendee.STT = _context.Us.OrderBy(m => m.STT).Last().STT + 1;
                    newAttendee.PhoneNumber = PhoneNumber;
                    newAttendee.UsMssv = UsMssv;
                    newAttendee.FullName = FullName;
                    newAttendee.SchoolId = (int)SchoolId;
                    newAttendee.Email = user.Email;

                    _context.Us.Add(newAttendee);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Thêm thông tin thành công";
                }
                else
                {
                    TempData["error"] = "Thông tin đã tồn tại";
                }

            }
            return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeInfor(string PhoneNumber, string UsMssv, int? SchoolId, string FullName)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }
            if (PhoneNumber != null && UsMssv != null && SchoolId != null && FullName != null)
            {
                var atd = _context.Us.FirstOrDefault(m => m.Email.Equals(user.Email));
                if (atd == null)
                {
                    TempData["error"] = "Thông tin không tồn tại";
                }
                else
                {
                    var findMssv = _context.Us.Where(m => !m.Email.Equals(user.Email) && m.UsMssv.Trim().ToLower().Equals(UsMssv.Trim().ToLower())).Count();
                    if (findMssv > 0)
                    {
                        TempData["error"] = "Mã số sinh viên đã tồn tại";
                        return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
                    }

                    atd.STT = _context.Us.OrderBy(m => m.STT).Last().STT + 1;
                    atd.PhoneNumber = PhoneNumber;
                    atd.UsMssv = UsMssv;
                    atd.FullName = FullName;
                    atd.SchoolId = (int)SchoolId;

                    _context.Us.Update(atd);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Thay đổi thông tin thành công";
                }

            }
            return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterTalkshow()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Identity/Account/Login");
            }

            var now = DateTime.Now;
            var end = new DateTime(2024, 1, 22, 17, 59, 59);

            if (now > end || _context.Talkshows.Count() >= 320)
            {
                TempData["error"] = "Form đăng ký tham gia đã đóng do quá hạn hoặc đủ số lượng tham gia.";
                return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
            }

            var atd = _context.Us.FirstOrDefault(u => u.Email.Equals(user.Email) && u.UsMssv != null);
            /*var atd = _context.Us.FirstOrDefault(m => m.Id.Equals(user.Id));*/
            if (atd == null)
            {
                TempData["error"] = "Bạn phải thêm thông tin cá nhân trước.";
            }
            else
            {
                var registerUser = _context.Talkshows.FirstOrDefault(m => m.UserId.Equals(atd.Id));
                if (registerUser != null)
                {
                    TempData["error"] = "Bạn đã đăng ký tham gia Talkshow thành công, không thể đăng ký thêm.";
                }
                else
                {
                    Talkshow register = new Talkshow();
                    register.UserId = atd.Id;

                    _context.Talkshows.Add(register);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Bạn đã đăng ký tham gia Talkshow thành công!";

                    /*await _emailSender.SendEmailAsync(
                        user.Email,
                        "[NO-REPLY] Đăng ký tham gia Talkshow S.T.A.M.P 2023",
                        $"Bạn đã đăng ký tham gia Talkshow S.T.A.M.P 2023 thành công. Nếu đây không phải hoạt động của bạn, vui lòng xóa email này.");*/
                }
            }          
            return LocalRedirect("~/Talkshow/HomeRegisterTalkshow");
        }
    }
}

Views/Exhibition/Exhibition.cshtml
@model IEnumerable<BIT_STAMP.Models.Product>
@{
    ViewData["Title"] = "Triển lãm tại sảnh";
}
<div class="row exhibition justify-content-center">
    @* <div class="col-lg-6 col-md-12 col-sm-12">

    </div> *@
    @* <div class="goto-ex col-lg-6 col-md-12 col-sm-12">
        <a class="countdown-button" style="text-decoration:none" href="https://forms.gle/orwdQdhBkBvacweD6">TỚI KHU TRIỂN LÃM</a>
    </div> *@@* 
    <br />
    <br />
    <br /> *@

    <h2 class="blue-color part-margin blur-shadow">BÌNH CHỌN TÁC PHẨM TRIỂN LÃM TẠI SẢNH B1</h2>
    <img class="line" src="~/image/shared/line.png" />
    <br/>
    <h3>Đã hết thời hạn bình chọn tác phẩm triển lãm tại sảnh, hẹn gặp lại bạn ở các hoạt động tiếp theo của BIT.</h3><br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    @* @if (ViewBag.atd != null)
    {
        @if (ViewBag.RegisterUser != null)
        {
            <h3>Bạn đã bình chọn thành công, cảm ơn bạn đã quan tâm chương trình.</h3>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        }
        else
        {
            <div class="offline-voting">
                <form method="post" asp-controller="Exhibition" asp-action="Exhibition" enctype="multipart/form-data">
                    <div class="row form-group justify-content-center">
                        <div class="col-4 text-align-left">
                            <div class="label-information">Minh chứng đã Like fanpage Đoàn - Hội khoa Công nghệ thông tin kinh doanh</div>
                        </div>
                        <div class="col-3">
                            <input accept="image/*" type="file" name="likefanpageImg" class="form-control" required />
                        </div>
                    </div>
                    <br/>
                    <div class="row form-group justify-content-center">
                        <div class="col-4 text-align-left">
                            <div class="label-information">Minh chứng đã up Story kèm Hashtag #BIT #STAMP2023 #ARTSTEPSSTAMP</div>
                        </div>
                        <div class="col-3">
                            <input accept="image/*" type="file" name="upstoryImg" class="form-control" required />
                        </div>
                    </div>
                    <br/>
                    <h4><b>Hãy cho chúng mình biết tác phẩm bạn yêu thích là gì nhé!</b></h4>
                    <div class="row justify-content-center add-info">
                        @foreach (var item in Model)
                        {
                            <div class="col-lg-4 col-md-12 col-sm-12 text-align-left align-self-center">
                                <div class="row">
                                    <div class="col-1 align-self-center">
                                        <input class="vote-check-box" id="@item.ProductId" type="checkbox" name="@item.ProductId" style="accent-color:black;width:20px;" value="@item.ProductName" />
                                    </div>
                                    <div class="col-4">
                                        <div class="stamp-frame" onclick="showInforRanking(@item.ProductId)">
                                            <img class="stamp-img" src="data:image /jpeg;base64,@(Convert.ToBase64String(item.ImageUrl))" alt="product-item">
                                        </div>
                                    </div>
                                    <div class="col-7 align-self-center">
                                        <label class="label-information" for="@item.ProductId">@item.ProductName</label>
                                    </div>
                                </div>                                
                                <br />
                            </div>
                        }                        
                    </div>

                    <input class="save-button" type="submit" value="Xác nhận" />
                </form>
            </div>
        }

    }
    else
    {
        <div class="add-info">
            <br />
            <h3>Để tham gia bình chọn, bạn cần điền thông tin cá nhân trước tại <a class="goto-link item" asp-area="" asp-controller="Talkshow" asp-action="HomeRegisterTalkshow">ĐÂY</a> theo hướng dẫn sau:</h3>
            <br />
            <h4>Bước 1: Ấn vào nút hình bánh răng để mở giao diện bổ sung thông tin cá nhân.</h4>
            <img class="settings-img" src="~/image/exhi/setting-button.png" />
            <br/>
            <h4>Bước 2: Điền thông tin cá nhân nếu các trường thông tin trống.</h4>
            <img class="popup-img" src="~/image/exhi/info-popup.png" />
            <br/>
            <h4>Bước 3: Nhấn Lưu thông tin để hoàn tất và quay lại trang này để tiếp tục bình chọn.</h4>
        </div>
    } *@

    
</div>
@section Styles{
    <link rel="stylesheet" href="~/css/exhibition.css" asp-append-version="true" />
}